name: RodentLabs
favicon: null
layout_spectrum: 0.25944225979037583
typography_spectrum: 0.6408378793857992
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.11663381056860089
  lightness: 0.887642968678847
  saturation: 0.07810626900754869
  rhythmicContrast: 0.2877329345792532
purpose: []
